settings:
  title: 'Dimdata Status'
  url: 'https://status.dimdata.com' # used for Slack messages
  logo: 'https://www.dimdata.com/assets/images/logo/dimdata-logo.svg' # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: webapi-dimdata-com # unique identifier
    name: API (asia-southeast1 region)
    description: 'Core API, Database, and storage.' # default=empty
    url: 'https://webapi.dimdata.com/api/live' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link,default=true
    
  - id: searchapi-dimdata-com # unique identifier
    name: API (asia-southeast1 region)
    description: 'Search and Indexing API' # default=empty
    url: 'https://searchapi.dimdata.com/api/live' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link,default=true
    
  - id: account-dimdata-com # unique identifier
    name: Authorization Server (asia-southeast1 region)
    description: 'Authorization Server and Account API' # default=empty
    url: 'https://account.dimdata.com/Account/Login/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: app-dimdata-com
    name: Web Application (app.dimdata.com)
    description: 'Web Application'
    url: 'https://app.dimdata.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false
    
  - id: www-dimdata-com
    name: www.dimdata.com
    description: 'Dimdata.com Website'
    url: 'https://www.dimdata.com/en/'
    method: GET
    expectStatus: 200
